variables:
  PROJECT_NAME: "RGB"
before_script:
  - echo "starting build for %PROJECT_NAME%"
  - echo "Restoring NuGet Packages..."
  - D:\dev\runner\nuget restore "%PROJECT_NAME%.sln" -Source https://www.myget.org/F/rgb_net/api/v3/index.json
stages:
  - build
  - test
build:
  stage: build
  script:
  - echo "Release build..."
  - '"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe" /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet "%PROJECT_NAME%.sln"'
  artifacts:
    paths:
    - RGB/bin/Release/*
    expire_in: 1 week
#test:
#  stage: test
#  script:
#  - echo "starting tests"
#  - cd %PROJECT_NAME%Tests/bin/Release
#  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\MSTest.exe" /testcontainer:%PROJECT_NAME%Tests.dll'
#  dependencies:
#  - build
